### ISSUE TITLE
Doubts about opening jupyter

### ISSUE THREAD

**Issue by z626093820** [jackievaleri/BioAutoMATED#3]
When I open BioAutoMATED in docker on windows 11 platform, jupyter prompts me for a password and token but I don't have this set up, how do I fix this please, thank you in advance!

First I clicked on 8888:8888，it show the browser

![image](https://github.com/jackievaleri/BioAutoMATED/assets/37371455/88a10ac7-90f7-4fdb-bba0-0ed2ed4b4494)

![image](https://github.com/jackievaleri/BioAutoMATED/assets/37371455/6be6b115-e155-4069-bed4-90e4010b2bbc)

**Comment by jackievaleri** [comment]
Hi, sorry to hear you are having issues. The current Dockerfile specifies that both the token and password are empty strings (''). If you setup a new password using an empty token, are you able to login? Could you also check that you are not currently running anything else on port 8888?

If this does not work, I can build a new Docker image for you with a set password and we can see if that fixes the problem. I have been traveling and will be unavailable next week, but I can do this the week of August 14th if necessary. Please let me know if you are able to resolve the issue before then!

**Comment by z626093820** [comment]
Hello, thanks for your help, this seems to be a problem with jupyter and it was solved by setting the jupyter password!

**Comment by z626093820** [comment]
> Hi, sorry to hear you are having issues. The current Dockerfile specifies that both the token and password are empty strings (''). If you setup a new password using an empty token, are you able to login? Could you also check that you are not currently running anything else on port 8888?
> 
> If this does not work, I can build a new Docker image for you with a set password and we can see if that fixes the problem. I have been traveling and will be unavailable next week, but I can do this the week of August 14th if necessary. Please let me know if you are able to resolve the issue before then!

Hello, thanks for your help, this seems to be a problem with jupyter and it was solved by setting the jupyter password!

**Comment by jackievaleri** [comment]
Awesome! Glad to hear the problem resolved. Please feel free to open another issue if you encounter additional problems. For now I will close this issue!
